// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/Decrypt.tsx";
import * as $$$$$$$$$1 from "./actions/Encrypt.tsx";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/Hero.tsx";
import * as $$$$$$2 from "./sections/ItWorks.tsx";
import * as $$$$$$3 from "./sections/Members.tsx";
import * as $$$$$$4 from "./sections/Picker.tsx";
import * as $$$$$$5 from "./sections/Team.tsx";
import * as $$$$$$6 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/Hero.tsx": $$$$$$1,
    "site/sections/ItWorks.tsx": $$$$$$2,
    "site/sections/Members.tsx": $$$$$$3,
    "site/sections/Picker.tsx": $$$$$$4,
    "site/sections/Team.tsx": $$$$$$5,
    "site/sections/Theme/Theme.tsx": $$$$$$6,
  },
  "actions": {
    "site/actions/Decrypt.tsx": $$$$$$$$$0,
    "site/actions/Encrypt.tsx": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
